Repository AppleBoiy/cs203-covid19-analysis-2023, pull requests merged in 2023-09, with the labels that each got.

#17 Update README.md
  .github/README.md
Labels: enhancement, testing

#22 Dev
  .github/workflows/dependency-review.yml
  .github/workflows/python.yml
  .prettierrc
  code/ranking.ipynb
  sample/PTCTEST1.ipynb
  sample/PTCTEST2.ipynb
Labels: documentation, testing

#24 master
  .github/CODE_OF_CONDUCT.md
  LICENSE
Labels: documentation

#25 document update
  .github/CONTRIBUTORS.md
  .github/README-TH.md
  .github/README.md
Labels: documentation

#26 docs
  .github/README-TH.md
  .github/README.md
Labels: documentation

#28 Dev
  .github/README.md
  .github/docs/refs.md
  .github/flavor.css
  .github/toc.css
Labels: documentation

#29 Docs
  .github/README.md
  .github/docs/refs.md
Labels: documentation

#30 Dev
  .github/README.md
  .github/docs/refs.md
Labels: documentation

#31 docs
  .github/README.md
Labels: documentation

#34 Docs
  .github/README.md
  resource/etc/sort_by_total_confirm.png
Labels: documentation

#39 Code coverage, linting and testing job separately
  .github/workflows/dependency-review.yml
  .github/workflows/python.yml
  .github/workflows/testing-linting.yml
  README.md
Labels: documentation, enhancement, testing

#40 add code coverage, Linting and Unit testing job separately
  .github/workflows/dependency-review.yml
  .github/workflows/python.yml
  .github/workflows/testing-linting.yml
  README.md
  code/ranking.ipynb
  code/ranking2.ipynb
Labels: documentation, enhancement, testing

#41 codecov/actions@v4 won't work downgrade to v3
  .github/workflows/testing-linting.yml
Labels: bug

#42 parallel os unit test, create setup.cfg and use processor.py instead of setup.py (duplicated name in api/setup.py)
  .flake8
  .github/README-TH.md
  .github/README.md
  .github/docs/prerequisites.md
  .github/workflows/testing-linting.yml
  processor.py
  setup.cfg
  src/validator.py
Labels: bug, enhancement, testing

#43 Add test/lint badge, change action name to Unit tests
  .github/README.md
  .github/workflows/testing-linting.yml
  code/ranking2.ipynb
Labels: documentation, enhancement
